sonar.projectKey=Jungsunmin_OOAD_TeamProj
sonar.organization=konkukooad

sonar.sources=src
sonar.tests=tests
sonar.cfamily.compile-commands=build/compile_commands.json

sonar.coverageReportPaths=coverage.xml
sonar.cpp.cppcheck.reportPaths=reports/cppcheck.xml
sonar.cpp.clangtidy.reportPaths=clang-tidy-report.txt