sonar.projectKey=Jungsunmin_OOAD_TeamProj
sonar.organization=konkukooad

sonar.sources=src
sonar.tests=tests
sonar.cfamily.compile-commands=build/compile_commands.json

sonar.cfamily.gcov.reportsPath=build	#gcov 커버리지
sonar.cppcheck.reportPath=cppcheck-report.xml	#cppcheck 보고서
sonar.clangtidy.reportPath=clang-tidy-report.txt	#clang-tidy 보고서